package com.mostapps.egyptianmeterstracker.utils


object MeterTariffUtils {

    const val HOME_ELECTRICITY_FIRST_SLICE_KWH_LIMIT = 50
    const val HOME_ELECTRICITY_FIRST_SLICE_MULTIPLIER = 0.48
    const val HOME_ELECTRICITY_FIRST_SLICE_CUSTOMER_SERVICE_FEE = 1

    const val HOME_ELECTRICITY_SECOND_SLICE_KWH_LIMIT = 100
    const val HOME_ELECTRICITY_SECOND_SLICE_MULTIPLIER = 0.58
    const val HOME_ELECTRICITY_SECOND_SLICE_CUSTOMER_SERVICE_FEE = 2

    const val HOME_ELECTRICITY_THIRD_SLICE_KWH_LIMIT = 200
    const val HOME_ELECTRICITY_THIRD_SLICE_MULTIPLIER = 0.77
    const val HOME_ELECTRICITY_THIRD_SLICE_CUSTOMER_SERVICE_FEE = 6

    const val HOME_ELECTRICITY_FOURTH_SLICE_KWH_LIMIT = 350
    const val HOME_ELECTRICITY_FOURTH_SLICE_MULTIPLIER = 1.06
    const val HOME_ELECTRICITY_FOURTH_SLICE_CUSTOMER_SERVICE_FEE = 11

    const val HOME_ELECTRICITY_FIFTH_SLICE_KWH_LIMIT = 650
    const val HOME_ELECTRICITY_FIFTH_SLICE_MULTIPLIER = 1.28
    const val HOME_ELECTRICITY_FIFTH_SLICE_CUSTOMER_SERVICE_FEE = 15

    const val HOME_ELECTRICITY_SIXTH_SLICE_KWH_LIMIT = 1000
    const val HOME_ELECTRICITY_SIXTH_SLICE_MULTIPLIER = 1.28
    const val HOME_ELECTRICITY_SIXTH_SLICE_CUSTOMER_SERVICE_FEE = 25

    const val HOME_ELECTRICITY_SEVENTH_SLICE_MULTIPLIER = 1.45
    const val HOME_ELECTRICITY_SEVENTH_SLICE_CUSTOMER_SERVICE_FEE = 40


    const val COMMERCIAL_ELECTRICITY_FIRST_SLICE_KWH_LIMIT = 100
    const val COMMERCIAL_ELECTRICITY_FIRST_SLICE_MULTIPLIER = 0.65
    const val COMMERCIAL_ELECTRICITY_FIRST_SLICE_CUSTOMER_SERVICE_FEE = 5

    const val COMMERCIAL_ELECTRICITY_SECOND_SLICE_KWH_LIMIT = 250
    const val COMMERCIAL_ELECTRICITY_SECOND_SLICE_MULTIPLIER = 1.20
    const val COMMERCIAL_ELECTRICITY_SECOND_SLICE_CUSTOMER_SERVICE_FEE = 15

    const val COMMERCIAL_ELECTRICITY_THIRD_SLICE_KWH_LIMIT = 600
    const val COMMERCIAL_ELECTRICITY_THIRD_SLICE_MULTIPLIER = 1.40
    const val COMMERCIAL_ELECTRICITY_THIRD_SLICE_CUSTOMER_SERVICE_FEE = 20

    const val COMMERCIAL_ELECTRICITY_FOURTH_SLICE_KWH_LIMIT = 1000
    const val COMMERCIAL_ELECTRICITY_FOURTH_SLICE_MULTIPLIER = 1.55
    const val COMMERCIAL_ELECTRICITY_FOURTH_SLICE_CUSTOMER_SERVICE_FEE = 25

    const val COMMERCIAL_ELECTRICITY_FIFTH_SLICE_MULTIPLIER = 1.60
    const val COMMERCIAL_ELECTRICITY_FIFTH_SLICE_CUSTOMER_SERVICE_FEE = 40


}